spring:
  application:
    name: inventory-service
  liquibase:
    enabled: true
    change-log: classpath:/db/inventory/changelog/db.changelog-master-inventory.yaml
  datasource:
    url: jdbc:postgresql://localhost:${DB_INVENTORY_PORT:5433}/products_db
    username: admin
    password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        logging:
          level:
            sql: DEBUG
  grpc:
    server:
      port: ${GRPC_INVENTORY_PORT:9090}
      security:
        csrf:
          enabled: false

  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT:9092}
    consumer:
      group-id: inventory-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Автоматическая инструментация консюмера
        interceptor.classes: io.opentelemetry.instrumentation.kafkaclients.TracingConsumerInterceptor
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Автоматическая инструментация продюсера
        interceptor.classes: io.opentelemetry.instrumentation.kafkaclients.TracingProducerInterceptor
    listener:
      observation-enabled: true   # Включает наблюдение за консюмерами
    template:
      observation-enabled: true   # Включает наблюдение за продюсерами

admin:
  apikey: "admin-key"
server:
  port: ${INVENTORY_SERVICE_PORT:8081}


management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:${TEMPO_OTLP_PORT:4318}/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://localhost:${TEMPO_OTLP_PORT:4318}/v1/traces
    resource-attributes:
      service:
        name: inventory-service
  otlp:
    metrics:
      export:
        url: http://localhost:${TEMPO_OTLP_PORT:4318}/v1/metrics

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - trace_id=%X{trace_id} span_id=%X{span_id} - %msg%n"
  level:
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.common.config: WARN
    com.bezrukov: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.kafka: WARN